#!/usr/bin/env python3
"""D5c-1 — generate contracts/test/halmos/XPNTsV2Selectors.sol from the forge artifacts.

The partition "OTHER" of the xPNTs harness (XPNTsV2HalmosBase._partition) is: empty calldata, or the
1028-byte symbolic-selector input whose selector is NOT any selector of the core OR the extension
ABI (views included). This file lists those selectors. D5c1ReplayTest.test_D5c1_selectorListMatchesArtifacts
re-derives the list from out/ and fails if it is stale.

usage (repo root, after a build): python3 script/halmos/gen-selectors.py
"""
import json

sels = {}
for n in ["xPNTsTokenV2", "xPNTsTokenV2Ext"]:
    d = json.load(open(f"out/{n}.sol/{n}.json"))
    for sig, sel in d["methodIdentifiers"].items():
        sels[sel] = sig
rows = sorted(sels.items(), key=lambda x: x[1])
lines = [
    "// SPDX-License-Identifier: Apache-2.0",
    "pragma solidity 0.8.33;",
    "",
    "// GENERATED by script/halmos/gen-selectors.py from out/xPNTsTokenV2*.json — do not edit.",
    f"// {len(rows)} selectors = methodIdentifiers of xPNTsTokenV2 UNION xPNTsTokenV2Ext (views included).",
    "library XPNTsV2Selectors {",
    f"    uint256 internal constant COUNT = {len(rows)};",
    "",
    "    /// @dev 1 if `s` is a selector of either ABI, else 0 — branch-free (no JUMPI on `s`).",
    "    function isKnown(bytes4 s) internal pure returns (uint256 k) {",
    "        assembly {",
    "            let x := shr(224, s)",
]
for sel, sig in rows:
    lines.append(f"            k := or(k, eq(x, 0x{sel})) // {sig}")
lines += [
    "        }",
    "    }",
    "",
    "    function all() internal pure returns (bytes4[] memory a) {",
    f"        a = new bytes4[]({len(rows)});",
]
for i, (sel, sig) in enumerate(rows):
    lines.append(f"        a[{i}] = 0x{sel};")
lines += ["    }", "}", ""]
open("contracts/test/halmos/XPNTsV2Selectors.sol", "w").write("\n".join(lines))
print(f"wrote {len(rows)} selectors")
